### ISSUE TITLE
Eigenvalues did not converge

### ISSUE THREAD

**Issue by yuyingg0921** [davidhallac/TICC#22]
Hello!
because I am trying to test my data in your example.py
but I got an error:
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
Do you know what's wrong with this?
Thank you very much

**Comment by davidhallac** [comment]
Hi! I just ran the example.py code and it seems to be working fine for me… Did you change anything in the code? And can you show what the terminal prints when you get this error?

**Comment by yuyingg0921** [comment]
Yes, sometimes I ran the example.py and it's fine, but sometimes it's not. (different dataset)
Is there any constraint about the input time series data?
And the picture below shows another error QQ
(when I set different w, the error may sometimes occurs.)
https://i.imgur.com/iifZ4y3.png
thank you very much!!!

**Comment by davidhallac** [comment]
Hmm, are you sure you've pulled the most recent version of the TICC solver? We've pushed some bug fixes over the past couple weeks that might be contributing to this error.

There are no constraints on the input time series, but I've seen similar errors when the dataset is poorly scaled with the problem hyperparameters... The original example dataset should work perfectly, right? Do you have a specific dataset that this is happening on? If you are able to share a specific example of when this error occurs, I can look more closely using that separate dataset and try to see what is going wrong.

Thanks!

**Comment by yuyingg0921** [comment]
oh! sorry I didn't notice that you pulled the new version.
It works pretty good now, this paper is really awesome!
The clustering result looks nice.
Sometimes the error may still occur , but as you said, I think the reason is the chosen of hyperparameters.
thank you very much!

**Comment by davidhallac** [comment]
Great! Yes, the error may occasionally occur with poorly tuned hyperparameters, but in general the newest code should fix it. Thanks!
